import Image from 'next/image';

const CONNECTED = [
  {
    label: 'Booking details',
    desc: 'Dates, vehicle, driver info, and rental value — all the context your team needs, in one operational view.',
  },
  {
    label: 'Automated reminders',
    desc: 'Pre-pickup and return reminders fire automatically. No manual scheduling, no one forgetting to send them.',
  },
  {
    label: 'Guest portal and return instructions',
    desc: 'A branded guest page is generated for every booking — vehicle guide, pickup info, return instructions, and guest responsibilities.',
  },
  {
    label: 'Checklists and photo evidence',
    desc: 'Pre-rental prep and return inspection checklists, with photo capture at handover. A timestamped record tied to the booking.',
  },
];

export default function BookingFlowSection() {
  return (
    <section
      className="py-20 lg:py-28 border-t"
      style={{ backgroundColor: 'var(--surface-blue-pale)', borderColor: 'var(--border-blue-light)' }}
    >
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">

        <div className="grid lg:grid-cols-2 gap-12 lg:gap-20 items-start">

          {/* Left: copy */}
          <div className="max-w-lg">
            <div
              className="inline-block px-3 py-1 rounded-full text-[11px] font-semibold uppercase tracking-widest mb-5 border"
              style={{ backgroundColor: 'var(--surface-white)', borderColor: 'var(--border-blue-light)', color: 'var(--blue-brand)' }}
            >
              Works with your existing system
            </div>

            <h2
              className="text-[28px] sm:text-[36px] font-bold tracking-tight leading-tight mb-5"
              style={{ color: 'var(--on-light-primary)' }}
            >
              Everything tied to the booking. Nothing falls through the gaps.
            </h2>

            <p className="text-[17px] leading-relaxed mb-6" style={{ color: 'var(--on-light-secondary)' }}>
              CamperFlow doesn&apos;t replace your booking software. Most booking platforms can export data as CSV, iCal, or JSON — whichever your system supports, that&apos;s how bookings come across. Once a rental is confirmed inside CamperFlow, it becomes an operational hub: reminders fire from it, the guest portal is generated by it, checklists are assigned to it, and vehicle status flows through it.
            </p>

            <div
              className="flex items-start gap-3 px-4 py-3.5 rounded-xl border mb-8"
              style={{ backgroundColor: 'var(--surface-white)', borderColor: 'var(--border-light)' }}
            >
              <svg viewBox="0 0 20 20" fill="none" stroke="currentColor" strokeWidth={1.5} strokeLinecap="round" strokeLinejoin="round" className="w-4 h-4 flex-shrink-0 mt-0.5" style={{ color: 'var(--blue-brand)' }}>
                <rect x="3" y="5" width="14" height="10" rx="2" />
                <path d="M7 15v2M13 15v2M5 17h10" />
              </svg>
              <p className="text-[13px] leading-relaxed" style={{ color: 'var(--on-light-muted)' }}>
                <span className="font-semibold" style={{ color: 'var(--on-light-primary)' }}>Staff use any device they already own.</span>{' '}
                Phone, tablet, or laptop — log in, complete checklists, upload photos, and mark tasks done. CamperFlow updates the operational state automatically.
              </p>
            </div>

            <div className="space-y-3 mb-8">
              {CONNECTED.map((item, i) => (
                <div
                  key={i}
                  className="flex gap-3 p-4 rounded-xl border"
                  style={{ backgroundColor: 'var(--surface-white)', borderColor: 'var(--border-blue-light)' }}
                >
                  <div
                    className="w-5 h-5 rounded-full flex items-center justify-center flex-shrink-0 mt-0.5"
                    style={{ backgroundColor: 'var(--blue-brand)' }}
                  >
                    <svg viewBox="0 0 10 10" fill="none" stroke="white" strokeWidth={2} strokeLinecap="round" className="w-2.5 h-2.5">
                      <path d="M1.5 5l2.5 2.5 4.5-4.5" />
                    </svg>
                  </div>
                  <div>
                    <div className="text-[14px] font-semibold mb-0.5" style={{ color: 'var(--on-light-primary)' }}>
                      {item.label}
                    </div>
                    <div className="text-[13px] leading-relaxed" style={{ color: 'var(--on-light-muted)' }}>
                      {item.desc}
                    </div>
                  </div>
                </div>
              ))}
            </div>

            <a
              href="#cta"
              className="inline-flex items-center gap-2 text-[14px] font-semibold"
              style={{ color: 'var(--blue-brand)' }}
            >
              See it in a demo
              <svg viewBox="0 0 16 16" fill="none" stroke="currentColor" strokeWidth={2} strokeLinecap="round" strokeLinejoin="round" className="w-4 h-4">
                <path d="M3 8h10M8 3l5 5-5 5" />
              </svg>
            </a>
          </div>

          {/* Right: booking-details.png — tall, operationally deep */}
          <div className="lg:sticky lg:top-24">
            <div
              className="rounded-2xl overflow-hidden border"
              style={{
                borderColor: 'var(--border-blue-light)',
                boxShadow: '0 16px 48px rgba(37,99,235,0.10), 0 2px 8px rgba(0,0,0,0.06)',
              }}
            >
              {/* Browser chrome */}
              <div
                className="flex items-center gap-3 px-4 py-2.5 border-b"
                style={{ backgroundColor: 'var(--surface-light)', borderColor: 'var(--border-light)' }}
              >
                <div className="flex gap-1.5">
                  <div className="w-2.5 h-2.5 rounded-full" style={{ backgroundColor: '#fca5a5' }} />
                  <div className="w-2.5 h-2.5 rounded-full" style={{ backgroundColor: '#fcd34d' }} />
                  <div className="w-2.5 h-2.5 rounded-full" style={{ backgroundColor: '#86efac' }} />
                </div>
                <div className="flex-1 text-center text-[11px] font-mono" style={{ color: 'var(--on-light-muted)' }}>
                  camperflow.io/bookings/BK-0041
                </div>
              </div>

              {/* booking-details.png — tall, readable, shows full connected booking view */}
              <div style={{ maxHeight: '700px', overflow: 'hidden' }}>
                <Image
                  src="/screenshots/booking-details.png"
                  alt="CamperFlow booking details — connected booking view with reminders, guest portal, checklists, and operational status"
                  width={2561}
                  height={4000}
                  style={{ width: '100%', height: 'auto', display: 'block' }}
                />
              </div>
            </div>
          </div>

        </div>
      </div>
    </section>
  );
}
